name: rfgb
channels:
  - defaults
dependencies:
  - appdirs=1.4.3
  - attrs=19.3.0
  - backcall=0.1.0
  - black=19.10b0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - click=7.0
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - fastcache=1.1.0
  - freetype=2.9.1
  - gmp=6.1.2
  - gmpy2=2.0.8
  - importlib_metadata=1.5.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - json5=0.9.1
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libpng=1.6.37
  - libsodium=1.0.16
  - llvmlite=0.31.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.1.0
  - mypy=0.750
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - notebook=6.0.3
  - numba=0.48.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pandas=1.0.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.1
  - pathspec=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - pygments=2.5.2
  - pyparsing=2.4.6
  - pyrsistent=0.15.7
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=18.1.1
  - readline=7.0
  - regex=2020.2.20
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=46.0.0
  - six=1.14.0
  - sqlite=3.31.1
  - sympy=1.5.1
  - tbb=2020.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toml=0.10.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.1
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - pip:
      - absl-py==0.9.0
      - jax==0.1.59
      - jaxlib==0.1.40
      - opt-einsum==3.2.0
